[package]
name = "clustiflor"
version = "1.0.4"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "clustiflor-cli"
path = "src/main.rs"

[dependencies]
rand = "0.10.1"
ndarray = "0.17.2"
walkdir = "2.5.0"
terminal_size = "0.4.4"
clap = { version = "4.6.1", features = ["derive"] }
colored = "3"